### PR TITLE
Update TpsCommand.java

### PR DESCRIPTION
**Pull request by LOLYAYDEV**
Fix Compability with 1.20.5/1.20.6

### CODE REVIEW

**Comment by LOLYAYDEV** [comment]
To fix #150

**Comment by mesacarlos** [comment]
Thank you very much for this PR. I'm pretty much out of the Java world already, I don't even have an Java IDE installed right now, so this PRs helping mantaining code are much appreciated.

**Comment by LOLYAYDEV** [comment]
You can close #150 now

**Comment by mesacarlos** [comment]
Yep, I'm still creating the release.
Automatic build is already complete: https://jenkins.mesacarlos.es/job/WebConsole/106/

**Pull request merged**
