### PR TITLE
Update to Version 2.2

### PR DESCRIPTION
**Pull request by awesomemoder316**
This solves the feature request in #79. 

I added the checks for commands when before the commands are executed, so as to filter out any whitelisted/blacklisted commands.

Limitations: No alias support. So even if I whitelist "whisper", the user will not be able to execute "/w" unless explicitly added. 

TODO: Update the client. I didn't touch the client as I'm not versed in Js, HTML, and CSS. A simple version bump should suffice.

### CODE REVIEW

**Comment by mesacarlos** [comment]
Thank you for your contribution!
Currently I'm away from home so I can't run the plugin nor update the client. I'll merge this PR this Saturday.

And again, thank you!

**Comment by awesomemoder316** [comment]
I realised that in your last commit, you made it so that the command sent has to exactly match the whitelisted command. I initially made it so that the command does not need to exactly match. (i.e. "/gamemode creative awesomemoder" will work even though the whitelist allows "/gamemode creative"). This is so that subcommands are allowed. Should this require another toggle? (E.g. a value in playerData called isStrictWhitelist)

**Comment by mesacarlos** [comment]
I did that change because when I was testing the other implementation, some commands were not working for some reason, for example the whisper command. The other command "gamemode survival playername" worked perfectly.
That's why I modified the code to solve the problem.

I tested this new code and it allows me to execute, for example "gamemode survival myUsername", with the whitelist enabled.

Maybe I'm not understanding something correctly. Was that the expected behavior?

**Comment by awesomemoder316** [comment]
Never mind, disregard my previous message. I was using Blacklist mode on accident >.<

**Comment by awesomemoder316** [comment]
Though I realised that the instructions on readme.md line 60 is now inaccurate since the admin: password is no longer used. Also, is it weird that for admins, passwords have to be set as 

``` 
admin:
  user: 
    password: securePassword
```

while for viewers it is 

```
viewer:
  user: securePassword
```
(no consistency in how to set pw.)

**Comment by mesacarlos** [comment]
Fixed.
I thought about it, and I think that the most reasonable change is to simplify the config file removing completely the viewers: section and just leave a section like 'users:' with all the info

Example:

```
useSSL: false
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: storepassword
KeyPassword: keypassword
host: 0.0.0.0
port: 8080
language: en
users:
	user1:
		password: mySecurePassword
		admin: true
		commandWhitelist:
			enabled: true
			commandWhitelistActsAsBlacklist: false
			whitelist:
				- whisper
				- gamemode survival
	user2:
		password: mySecurePassword2
		admin: false
		commandWhitelist:
			enabled: true
			commandWhitelistActsAsBlacklist: false
			whitelist:
				- whisper
				- gamemode survival
```

**Pull request merged**
