### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by steviebeenz**
Add hosted Webconsole.

### CODE REVIEW

**Comment by steviebeenz** [comment]
@mesacarlos Note that this is currently running my material design branch that I have in the pull request, I can put it to the standard branch if wanted.

**Comment by steviebeenz** [comment]
@mesacarlos the hosted build no longer removes your Translate, rather it uses https://github.com/mesacarlos/WebConsole/pull/32

**Comment by steviebeenz** [comment]
@mesacarlos I have moved to render to prevent rate limits.

**Comment by mesacarlos** [comment]
I'll think about this but I think that a lot of users do not update their plugins in a while and forcing them to always use the last version is not completely correct.

**Pull request closed without merging**
